In [1]:
%pip install numpy pandas

import numpy as np
import pandas as pd
from pathlib import Path

Requirement already satisfied: numpy in C:\Users\michael\AppData\Roaming\Python\Python313\site-packages (2.3.4)
Requirement already satisfied: pandas in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
BASE_PATH = Path(r"D:/DATASETS/cnn-lstm")

INPUT_BINARY = BASE_PATH / "dataset_binary.bin"
INPUT_INDEX = BASE_PATH / "dataset_index.csv"

OUTPUT_BINARY = BASE_PATH / "processed_dataset_binary.bin"
OUTPUT_INDEX = BASE_PATH / "processed_dataset_index.csv"

SAMPLE_RATE = 128                                       # Hz
WINDOW_SECONDS = 2                                      # window duration
WINDOW_OVERLAP = 0.5                                    # 50% overlap
SAMPLES_PER_WINDOW = int(SAMPLE_RATE * WINDOW_SECONDS)
STEP = int(SAMPLES_PER_WINDOW * (1 - WINDOW_OVERLAP))   # step size for sliding window
FREQUENCIES = np.arange(2.0, 40.5, 0.5)                 # target frequency bins

ELECTRODE_CHANNELS = ["Fp1","Fp2","F3","F4","C3",
                      "C4","P3","P4","O1","O2",
                      "F7","F8","T7","T8","P7",
                      "P8","Fz","Cz","Pz"]

In [3]:
# Load the index and memory-map the binary (lazy loading — no full read into RAM)
index_df = pd.read_csv(INPUT_INDEX)
data = np.memmap(INPUT_BINARY, dtype='float64', mode='r')

print(f"Index entries : {len(index_df)}")
print(f"Binary values : {len(data):,} float64")
print(f"Labels        : {index_df['label'].unique()}")
print(f"Columns       : {index_df.columns.tolist()}")

Index entries : 561
Binary values : 399,216,163 float64
Labels        : ['Control' 'ADHD-C' 'ADHD-I' 'ADHD-H']
Columns       : ['path', 'start_idx', 'length', 'rows', 'cols', 'label']

In [10]:
%pip install mne scikit-learn scipy

import mne

# Use a fixed component count: leave 1 degree of freedom (n_channels - 1)
ICA_N_COMPONENTS = len(["Fp1","Fp2","F3","F4","C3",
                         "C4","P3","P4","O1","O2",
                         "F7","F8","T7","T8","P7",
                         "P8","Fz","Cz","Pz"]) - 1  # = 18

def apply_ica_cleaning(df: pd.DataFrame, sfreq: float):
    """Apply ICA to remove muscle and eye artifacts from EEG dataframe."""

    ch_names = df.columns.tolist()
    ch_types = ["eeg"] * len(ch_names)
    info = mne.create_info(ch_names=ch_names, sfreq=sfreq, ch_types=ch_types)
    raw = mne.io.RawArray(df.to_numpy().T, info, verbose=False)

    # --- Filter for ICA (1–80 Hz typical) ---
    raw.filter(1.0, 60.0, fir_design="firwin", verbose=False)

    # --- Fit ICA ---
    ica = mne.preprocessing.ICA(n_components=ICA_N_COMPONENTS,
                                 method="fastica", verbose=False)
    ica.fit(raw, picks="eeg", decim=3)

    # --- Detect EOG-like (blink) components if present ---
    try:
        eog_inds, _ = ica.find_bads_eog(raw)
    except Exception:
        eog_inds = []

    # --- Detect muscle-like components (high-frequency ratio heuristic) ---
    sources = ica.get_sources(raw).get_data()
    n_ic = sources.shape[0]
    sfreq = raw.info["sfreq"]

    from scipy.signal import welch
    muscle_candidates = []
    for ic_idx in range(n_ic):
        f, Pxx = welch(sources[ic_idx], sfreq, nperseg=512)
        hf_mask = (f >= 20)
        hf_ratio = Pxx[hf_mask].sum() / np.sum(Pxx)
        if hf_ratio > 0.25:  # threshold – tune as needed
            muscle_candidates.append(ic_idx)

    exclude = list(set(eog_inds + muscle_candidates))
    ica.exclude = exclude
    if len(exclude) > 0:
        print(f"ICA removed components: {exclude}")
        raw_clean = ica.apply(raw.copy())
    else:
        print("No ICA components removed.")
        raw_clean = raw

    # --- Convert back to pandas DataFrame ---
    cleaned = pd.DataFrame(raw_clean.get_data().T, columns=ch_names)
    return cleaned

Requirement already satisfied: mne in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.10.2)
Requirement already satisfied: scikit-learn in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.7.1)
Requirement already satisfied: scipy in C:\Users\michael\AppData\Roaming\Python\Python313\site-packages (1.16.3)
Requirement already satisfied: decorator in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (5.2.1)
Requirement already satisfied: jinja2 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (3.1.6)
Requirement already satisfied: lazy-loader>=0.3 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (0.4)
Requirement already satisfied: matplotlib>=3.7 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (3.10.6)
Requirement already satisfied: numpy<3,>=1.25 in C:\Users\michael\AppData\Roaming\Python\Python313\site-packages (from mne) (2.3.4)
Requirement already satisfied: packaging in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (25.0)
Requirement already satisfied: pooch>=1.5 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (1.8.2)
Requirement already satisfied: tqdm in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mne) (4.67.1)
Requirement already satisfied: joblib>=1.2.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.7->mne) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pooch>=1.5->mne) (4.4.0)
Requirement already satisfied: requests>=2.19.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pooch>=1.5->mne) (2.32.5)
Requirement already satisfied: six>=1.5 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.7->mne) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.19.0->pooch>=1.5->mne) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.19.0->pooch>=1.5->mne) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.19.0->pooch>=1.5->mne) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.19.0->pooch>=1.5->mne) (2025.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->mne) (3.0.2)
Requirement already satisfied: colorama in c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->mne) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
def apply_filter(df: pd.DataFrame, lower=0.5, upper=30):
    electrode_columns = df.select_dtypes(include=[np.number]).columns

    n = len(df)
    freqs = np.fft.rfftfreq(n, d=1 / SAMPLE_RATE)
    filtered_df = df.copy()

    for electrode in electrode_columns:
        signal = df[electrode].to_numpy()
        fft_vals = np.fft.rfft(signal)
        fft_filter = (freqs >= lower) & (freqs <= upper)
        fft_vals[~fft_filter] = 0
        filtered_signal = np.fft.irfft(fft_vals, n=n)
        filtered_df[electrode] = filtered_signal

    return filtered_df

In [6]:
def process_window(window: pd.DataFrame) -> np.ndarray:
    """Convert a time-domain EEG window to frequency-domain power.

    Returns
    -------
    np.ndarray of shape (n_freqs, n_channels)
        Power spectrum interpolated to FREQUENCIES for each electrode.
    """
    n = len(window)
    original_freqs = np.fft.rfftfreq(n, d=1 / SAMPLE_RATE)

    power_matrix = np.zeros((len(FREQUENCIES), len(ELECTRODE_CHANNELS)),
                            dtype=np.float64)

    for ch_idx, electrode in enumerate(ELECTRODE_CHANNELS):
        sig = window[electrode].to_numpy()
        fft_vals = np.fft.rfft(sig)
        power = np.abs(fft_vals) ** 2
        power_matrix[:, ch_idx] = np.interp(FREQUENCIES, original_freqs, power)

    return power_matrix

In [7]:
def apply_ica_cleaning_to_dataset(df: pd.DataFrame):
    result_df = df.copy()
    numerical_df = df.select_dtypes(include=[np.number])
    cleaned_df = apply_ica_cleaning(numerical_df, SAMPLE_RATE)
    for col in numerical_df.columns:
        result_df[col] = cleaned_df[col]

    return cleaned_df

In [8]:
from scipy import signal
from scipy.integrate import simpson

# Define frequency bands (Hz)
bands = {
    'Theta':      (4,  8),
    'Alpha':      (8,  13),
    'Fast_Alpha': (8,  10),
    'Beta':       (13, 30),
    'High_Beta':  (15, 30),
}

# Broadband range used as the denominator for relative power
BROADBAND = (0.5, 40.0)


def compute_relative_band_powers(channel_data: np.ndarray, fs: float) -> dict:
    """Compute relative band power for all bands for a single channel.

    Relative power = band_power / total_broadband_power
    where total_broadband_power is integrated over BROADBAND.
    A single Welch PSD is computed and reused for all bands.
    """
    freqs, psd = signal.welch(channel_data, fs,
                              nperseg=min(256, len(channel_data)))

    # Total broadband power (denominator)
    bb_mask    = (freqs >= BROADBAND[0]) & (freqs <= BROADBAND[1])
    total_power = simpson(psd[bb_mask], freqs[bb_mask])

    rel_powers = {}
    for band_name, (low, high) in bands.items():
        idx = (freqs >= low) & (freqs <= high)
        abs_power = simpson(psd[idx], freqs[idx])
        rel_powers[band_name] = (abs_power / total_power
                                 if total_power > 0 else np.nan)

    return rel_powers

In [11]:
import gc

output_records = []   # rows for the output index CSV
output_offset  = 0    # running byte-offset into the output binary

with open(OUTPUT_BINARY, 'wb') as f_out:
    for i, row in index_df.iterrows():
        subject_id = Path(row['path']).stem
        label      = row['label']
        print(f"\n[{i+1}/{len(index_df)}] {subject_id}  ({label})")

        # ── 1. Lazy-load subject from binary ──────────────────────────
        chunk = data[row['start_idx'] : row['start_idx'] + row['length']]
        subject_df = pd.DataFrame(
            chunk.reshape(row['rows'], row['cols']),
            columns=ELECTRODE_CHANNELS,
        )

        # ── 2. Preprocessing pipeline ─────────────────────────────────
        subject_df = apply_filter(subject_df, 0.5, 30)          # bandpass
        subject_df = apply_ica_cleaning_to_dataset(subject_df)   # ICA artefact removal

        # ── 3. Per-subject relative band-power features (before z-norm) ──
        # Accumulate relative powers across channels, then average
        rel_acc = {b: 0.0 for b in bands}
        for ch in ELECTRODE_CHANNELS:
            ch_rel = compute_relative_band_powers(subject_df[ch].values, SAMPLE_RATE)
            for bname in bands:
                rel_acc[bname] += ch_rel[bname]
        for bname in rel_acc:
            rel_acc[bname] /= len(ELECTRODE_CHANNELS)

        # Relative-power ratios
        tbr = rel_acc['Theta'] / rel_acc['Beta']  if rel_acc['Beta']  else np.nan
        tar = rel_acc['Theta'] / rel_acc['Alpha'] if rel_acc['Alpha'] else np.nan

        # ── 4. Subject-wise z-score normalisation ─────────────────────
        subject_df = (subject_df - subject_df.mean()) / subject_df.std()

        # ── 5. Sliding-window FFT → write to binary ──────────────────
        n_samples  = len(subject_df)
        window_num = 0

        for start in range(0, n_samples - SAMPLES_PER_WINDOW + 1, STEP):
            window = subject_df.iloc[start : start + SAMPLES_PER_WINDOW]
            power_matrix = process_window(window)          # (n_freqs, n_channels)

            flat = power_matrix.ravel()                    # row-major
            flat.tofile(f_out)

            output_records.append({
                'id':              subject_id,
                'label':           label,
                'window':          window_num,
                'start_idx':       output_offset,
                'length':          flat.size,
                'rows':            power_matrix.shape[0],  # len(FREQUENCIES)
                'cols':            power_matrix.shape[1],  # len(ELECTRODE_CHANNELS)
                'rel_theta':       rel_acc['Theta'],
                'rel_alpha':       rel_acc['Alpha'],
                'rel_fast_alpha':  rel_acc['Fast_Alpha'],
                'rel_beta':        rel_acc['Beta'],
                'rel_high_beta':   rel_acc['High_Beta'],
                'tbr':             tbr,
                'tar':             tar,
            })
            output_offset += flat.size
            window_num    += 1

        print(f"  → {window_num} windows")
        del chunk, subject_df
        gc.collect()

print(f"\n{'='*50}")
print(f"Total windows written : {len(output_records)}")
print(f"Output binary values  : {output_offset:,}")

[1/561] v107  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 153 windows

[2/561] v108  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 147 windows

[3/561] v109  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [8, 10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 124 windows

[4/561] v10p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 110 windows

[5/561] v110  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 128 windows

[6/561] v111  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 118 windows

[7/561] v112  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 123 windows

[8/561] v113  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 120 windows

[9/561] v114  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 102 windows

[10/561] v115  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 121 windows

[11/561] v116  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 149 windows

[12/561] v117  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 199 windows

[13/561] v118  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.1s.
ICA removed components: [12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 92 windows

[14/561] v120  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 93 windows

[15/561] v121  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.5s.
No ICA components removed.
  → 126 windows

[16/561] v123  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 112 windows

[17/561] v125  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 119 windows

[18/561] v127  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [16, 11, 4, 7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components
  → 114 windows

[19/561] v129  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 86 windows

[20/561] v12p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 136 windows

[21/561] v131  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [2, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 129 windows

[22/561] v133  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 116 windows

[23/561] v134  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 103 windows

[24/561] v138  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 96 windows

[25/561] v140  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 133 windows

[26/561] v143  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 120 windows

[27/561] v147  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 110 windows

[28/561] v149  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [17, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 132 windows

[29/561] v14p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 136 windows

[30/561] v151  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 162 windows

[31/561] v15p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 336 windows

[32/561] v173  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 188 windows

[33/561] v177  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 129 windows

[34/561] v179  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [7, 8, 9, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 5 ICA components
    Projecting back using 19 PCA components
  → 98 windows

[35/561] v181  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 82 windows

[36/561] v183  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 144 windows

[37/561] v18p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 194 windows

[38/561] v190  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 119 windows

[39/561] v196  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 103 windows

[40/561] v198  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 152 windows

[41/561] v19p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 179 windows

[42/561] v1p  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 94 windows

[43/561] v200  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 98 windows

[44/561] v204  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 158 windows

[45/561] v206  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.4s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 156 windows

[46/561] v209  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 235 windows

[47/561] v20p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 275 windows

[48/561] v213  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 95 windows

[49/561] v215  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 165 windows

[50/561] v219  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [17, 10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 211 windows

[51/561] v21p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 128 windows

[52/561] v227  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 218 windows

[53/561] v22p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 93 windows

[54/561] v231  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 153 windows

[55/561] v234  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 266 windows

[56/561] v236  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 104 windows

[57/561] v238  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 75 windows

[58/561] v244  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 303 windows

[59/561] v246  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [17, 10, 7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 3 ICA components
    Projecting back using 19 PCA components
  → 165 windows

[60/561] v24p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 127 windows

[61/561] v250  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 107 windows

[62/561] v254  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.9s.
No ICA components removed.
  → 80 windows

[63/561] v25p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

Fitting ICA took 0.2s.
No ICA components removed.
  → 76 windows

[64/561] v263  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 144 windows

[65/561] v265  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 142 windows

[66/561] v270  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 184 windows

[67/561] v274  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [6]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 134 windows

[68/561] v279  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [9, 11]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 156 windows

[69/561] v27p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 224 windows

[70/561] v284  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 119 windows

[71/561] v286  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [10, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 88 windows

[72/561] v288  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 156 windows

[73/561] v28p  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [8]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 214 windows

[74/561] v297  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 106 windows

[75/561] v298  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 137 windows

[76/561] v299  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 172 windows

[77/561] v29p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 188 windows

[78/561] v300  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 202 windows

[79/561] v302  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 138 windows

[80/561] v303  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [8]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 149 windows

[81/561] v304  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 103 windows

[82/561] v305  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 173 windows

[83/561] v306  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 141 windows

[84/561] v307  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 177 windows

[85/561] v308  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.3s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 132 windows

[86/561] v309  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 192 windows

[87/561] v30p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 168 windows

[88/561] v310  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 138 windows

[89/561] v31p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.0s.
ICA removed components: [10, 11]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

  → 90 windows

[90/561] v32p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 140 windows

[91/561] v33p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 227 windows

[92/561] v34p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 151 windows

[93/561] v35p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 118 windows

[94/561] v36p  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [8, 4]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 134 windows

[95/561] v37p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 71 windows

[96/561] v38p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [9]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 191 windows

[97/561] v39p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.6s.
No ICA components removed.
  → 141 windows

[98/561] v3p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 261 windows

[99/561] v40p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 156 windows

[100/561] v41p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 96 windows

[101/561] v42p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 129 windows

[102/561] v43p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [2]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 98 windows

[103/561] v44p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 88 windows

[104/561] v45p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [11, 5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 83 windows

[105/561] v46p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 75 windows

[106/561] v47p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 83 windows

[107/561] v48p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 80 windows

[108/561] v49p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 130 windows

[109/561] v50p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 125 windows

[110/561] v51p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [8]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 61 windows

[111/561] v52p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 107 windows

[112/561] v53p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 148 windows

[113/561] v54p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
ICA removed components: [13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 149 windows

[114/561] v55p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 110 windows

[115/561] v56p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 109 windows

[116/561] v57p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 113 windows

[117/561] v58p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 107 windows

[118/561] v59p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 128 windows

[119/561] v60p  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.0s.
No ICA components removed.
  → 100 windows

[120/561] v6p  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 136 windows

[121/561] v8p  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 122 windows

[122/561] UB0004_entry0001  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 303 windows

[123/561] UB0004_entry0002  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[124/561] UB0004_entry0003  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[125/561] UB0020_entry0007  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[126/561] UB0020_entry0008  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[127/561] UB0020_entry0009  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[128/561] UB0021_entry0010  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[129/561] UB0021_entry0011  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[130/561] UB0021_entry0012  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[131/561] UB0022_entry0013  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[132/561] UB0022_entry0014  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[133/561] UB0022_entry0015  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[134/561] UB0023_entry0016  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[135/561] UB0023_entry0017  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[136/561] UB0023_entry0018  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[137/561] UB0024_entry0019  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[138/561] UB0024_entry0020  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[139/561] UB0024_entry0021  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[140/561] UB0025_entry0022  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[141/561] UB0025_entry0023  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[142/561] UB0026_entry0024  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[143/561] UB0026_entry0025  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[144/561] UB0026_entry0026  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[145/561] UB0027_entry0027  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[146/561] UB0027_entry0028  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [1]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[147/561] UB0027_entry0029  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[148/561] UB0028_entry0030  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[149/561] UB0028_entry0031  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[150/561] UB0028_entry0032  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[151/561] UB0029_entry0033  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [4]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[152/561] UB0029_entry0034  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [6]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[153/561] UB0029_entry0035  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [9, 5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[154/561] UB0030_entry0036  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [16, 9, 13, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[155/561] UB0030_entry0037  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [16, 12, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 3 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[156/561] UB0030_entry0038  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [8, 11, 13, 7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[157/561] UB0031_entry0039  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[158/561] UB0031_entry0040  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[159/561] UB0031_entry0041  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[160/561] UB0032_entry0042  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[161/561] UB0032_entry0043  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 702 windows

[162/561] UB0032_entry0044  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[163/561] UB0033_entry0045  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 3.1s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 304 windows

[164/561] UB0033_entry0046  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[165/561] UB0033_entry0047  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[166/561] UB0034_entry0048  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[167/561] UB0034_entry0049  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[168/561] UB0035_entry0050  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[169/561] UB0035_entry0051  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [16, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[170/561] UB0035_entry0052  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[171/561] UB0036_entry0053  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[172/561] UB0036_entry0054  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 304 windows

[173/561] UB0036_entry0055  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[174/561] UB0037_entry0056  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [11, 12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[175/561] UB0037_entry0057  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[176/561] UB0037_entry0058  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[177/561] UB0038_entry0059  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[178/561] UB0038_entry0060  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[179/561] UB0038_entry0061  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[180/561] UB0041_entry0065  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[181/561] UB0041_entry0066  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[182/561] UB0041_entry0067  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [11]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[183/561] UB0042_entry0068  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[184/561] UB0042_entry0069  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[185/561] UB0042_entry0070  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[186/561] UB0043_entry0071  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.0s.
No ICA components removed.
  → 304 windows

[187/561] UB0043_entry0072  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[188/561] UB0043_entry0073  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[189/561] UB0044_entry0074  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 307 windows

[190/561] UB0044_entry0075  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.6s.
No ICA components removed.
  → 1133 windows

[191/561] UB0044_entry0076  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[192/561] UB0045_entry0077  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[193/561] UB0045_entry0078  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[194/561] UB0046_entry0079  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [9, 4, 5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 3 ICA components
    Projecting back using 19 PCA components
  → 307 windows

[195/561] UB0046_entry0080  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[196/561] UB0046_entry0081  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [3, 4, 14, 7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components
  → 307 windows

[197/561] UB0047_entry0082  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[198/561] UB0047_entry0083  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[199/561] UB0047_entry0084  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[200/561] UB0050_entry0088  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[201/561] UB0050_entry0089  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[202/561] UB0050_entry0090  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[203/561] UB0051_entry0091  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[204/561] UB0051_entry0092  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[205/561] UB0051_entry0093  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[206/561] UB0052_entry0094  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[207/561] UB0052_entry0095  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[208/561] UB0052_entry0096  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[209/561] UB0056_entry0103  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 303 windows

[210/561] UB0056_entry0104  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[211/561] UB0056_entry0105  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 307 windows

[212/561] UB0057_entry0106  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[213/561] UB0057_entry0107  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 307 windows

[214/561] UB0057_entry0108  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[215/561] UB0060_entry0114  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[216/561] UB0060_entry0115  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[217/561] UB0061_entry0116  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.8s.
No ICA components removed.
  → 307 windows

[218/561] UB0061_entry0117  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 3.1s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 307 windows

[219/561] UB0061_entry0118  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 307 windows

[220/561] UB0062_entry0119  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
No ICA components removed.
  → 304 windows

[221/561] UB0062_entry0120  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[222/561] UB0062_entry0121  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[223/561] UB0064_entry0125  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[224/561] UB0064_entry0126  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[225/561] UB0064_entry0127  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 303 windows

[226/561] UB0066_entry0128  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[227/561] UB0066_entry0129  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[228/561] UB0066_entry0130  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 306 windows

[229/561] UB0067_entry0131  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[230/561] UB0067_entry0132  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[231/561] UB0067_entry0133  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[232/561] UB0068_entry0134  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[233/561] UB0068_entry0135  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[234/561] UB0068_entry0136  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[235/561] UB0069_entry0137  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[236/561] UB0069_entry0138  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[237/561] UB0069_entry0139  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[238/561] UB0070_entry0140  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[239/561] UB0070_entry0141  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[240/561] UB0070_entry0142  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[241/561] UB0071_entry0143  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[242/561] UB0071_entry0144  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 307 windows

[243/561] UB0071_entry0145  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[244/561] UB0072_entry0146  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 307 windows

[245/561] UB0072_entry0147  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[246/561] UB0072_entry0148  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 307 windows

[247/561] UB0073_entry0149  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[248/561] UB0073_entry0150  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[249/561] UB0073_entry0151  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[250/561] UB0074_entry0152  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[251/561] UB0074_entry0153  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[252/561] UB0074_entry0154  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[253/561] UB0075_entry0155  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[254/561] UB0075_entry0156  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[255/561] UB0075_entry0157  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[256/561] UB0076_entry0158  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[257/561] UB0076_entry0159  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [6]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[258/561] UB0076_entry0160  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 303 windows

[259/561] UB0077_entry0161  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[260/561] UB0077_entry0162  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[261/561] UB0077_entry0163  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[262/561] UB0078_entry0164  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 303 windows

[263/561] UB0079_entry0165  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[264/561] UB0079_entry0166  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[265/561] UB0079_entry0167  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[266/561] UB0080_entry0168  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 3.1s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 304 windows

[267/561] UB0080_entry0169  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[268/561] UB0080_entry0170  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [16, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[269/561] UB0081_entry0171  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[270/561] UB0081_entry0172  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[271/561] UB0081_entry0173  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[272/561] UB0082_entry0174  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[273/561] UB0082_entry0175  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[274/561] UB0082_entry0176  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[275/561] UB0084_entry0177  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[276/561] UB0084_entry0178  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[277/561] UB0084_entry0179  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[278/561] UB0085_entry0180  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[279/561] UB0085_entry0181  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
No ICA components removed.
  → 304 windows

[280/561] UB0085_entry0182  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[281/561] UB0086_entry0183  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[282/561] UB0086_entry0184  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[283/561] UB0086_entry0185  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[284/561] UB0087_entry0186  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[285/561] UB0087_entry0187  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[286/561] UB0087_entry0188  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[287/561] UB0088_entry0189  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[288/561] UB0088_entry0190  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[289/561] UB0088_entry0191  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[290/561] UB0090_entry0195  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[291/561] UB0090_entry0196  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[292/561] UB0090_entry0197  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[293/561] UB0091_entry0198  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[294/561] UB0091_entry0199  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[295/561] UB0091_entry0200  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[296/561] UB0092_entry0201  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[297/561] UB0092_entry0202  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[298/561] UB0092_entry0203  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[299/561] UB0094_entry0207  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[300/561] UB0094_entry0208  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[301/561] UB0094_entry0209  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 3.1s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 304 windows

[302/561] UB0095_entry0210  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[303/561] UB0095_entry0211  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[304/561] UB0095_entry0212  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[305/561] UB0096_entry0213  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[306/561] UB0096_entry0214  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[307/561] UB0096_entry0215  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[308/561] UB0097_entry0216  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[309/561] UB0097_entry0217  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[310/561] UB0097_entry0218  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[311/561] UB0098_entry0219  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[312/561] UB0098_entry0220  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[313/561] UB0099_entry0221  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[314/561] UB0099_entry0222  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[315/561] UB0099_entry0223  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[316/561] UB0100_entry0224  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[317/561] UB0100_entry0225  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[318/561] UB0100_entry0226  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[319/561] UB0102_entry0230  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[320/561] UB0102_entry0231  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[321/561] UB0102_entry0232  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[322/561] UB0103_entry0233  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[323/561] UB0103_entry0234  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[324/561] UB0103_entry0235  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[325/561] UB0106_entry0239  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[326/561] UB0106_entry0240  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[327/561] UB0106_entry0241  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[328/561] UB0107_entry0242  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[329/561] UB0107_entry0243  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[330/561] UB0107_entry0244  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[331/561] UB0109_entry0245  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[332/561] UB0109_entry0246  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[333/561] UB0109_entry0247  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[334/561] UB0110_entry0248  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[335/561] UB0110_entry0249  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[336/561] UB0110_entry0250  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[337/561] UB0111_entry0251  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[338/561] UB0111_entry0252  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[339/561] UB0111_entry0253  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[340/561] UB0113_entry0254  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[341/561] UB0113_entry0255  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[342/561] UB0113_entry0256  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[343/561] UB0115_entry0260  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[344/561] UB0115_entry0261  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [1]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[345/561] UB0115_entry0262  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[346/561] UB0116_entry0263  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[347/561] UB0116_entry0264  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[348/561] UB0116_entry0265  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[349/561] UB0117_entry0266  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[350/561] UB0117_entry0267  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[351/561] UB0117_entry0268  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[352/561] UB0118_entry0269  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[353/561] UB0118_entry0270  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[354/561] UB0118_entry0271  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[355/561] UB0119_entry0272  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[356/561] UB0119_entry0273  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[357/561] UB0119_entry0274  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[358/561] UB0120_entry0275  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[359/561] UB0120_entry0276  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[360/561] UB0120_entry0277  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[361/561] UB0121_entry0278  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[362/561] UB0121_entry0279  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[363/561] UB0121_entry0280  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[364/561] UB0122_entry0281  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[365/561] UB0122_entry0282  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[366/561] UB0122_entry0283  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[367/561] UB0124_entry0287  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[368/561] UB0124_entry0288  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[369/561] UB0124_entry0289  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[370/561] UB0125_entry0290  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[371/561] UB0125_entry0291  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[372/561] UB0125_entry0292  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[373/561] UB0127_entry0296  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [8, 6]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[374/561] UB0127_entry0297  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[375/561] UB0127_entry0298  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [6, 7]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[376/561] UB0128_entry0299  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [17, 10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 2 ICA components
    Projecting back using 19 PCA components
  → 304 windows

[377/561] UB0128_entry0300  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[378/561] UB0128_entry0301  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[379/561] UB0129_entry0302  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[380/561] UB0129_entry0303  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[381/561] UB0129_entry0304  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[382/561] UB0131_entry0305  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[383/561] UB0131_entry0306  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[384/561] UB0131_entry0307  (Control)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[385/561] UB0132_entry0308  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 304 windows

[480/561] UB0173_entry0410  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 1.6s.
No ICA components removed.
  → 304 windows

[481/561] UB0173_entry0411  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 3.1s.

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(

No ICA components removed.
  → 304 windows

[482/561] UB0174_entry0412  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[483/561] UB0174_entry0413  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[484/561] UB0174_entry0414  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [11]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 1 ICA component
    Projecting back using 19 PCA components
  → 304 windows

[485/561] UB0175_entry0415  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[486/561] UB0175_entry0416  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[487/561] UB0175_entry0417  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[488/561] UB0176_entry0418  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[489/561] UB0176_entry0419  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
No ICA components removed.
  → 304 windows

[490/561] UB0176_entry0420  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
No ICA components removed.
  → 304 windows

[491/561] sub-88007109_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 4, 5, 8, 9, 10, 12, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 10 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2.6e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[492/561] sub-88007241_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [0, 1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (14) and smallest (1e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[493/561] sub-88013089_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (17) and smallest (7.6e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[494/561] sub-88015881_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 5, 7, 8, 9, 11, 12, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (2.9e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[495/561] sub-88017633_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (2.7e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[496/561] sub-88018533_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [7, 8, 9, 12, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 5 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (2.2e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[497/561] sub-88019165_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [1, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[498/561] sub-88024205_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [16, 17, 13, 5]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.1e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[499/561] sub-88024205_ses-3_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (1.8e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[500/561] sub-88025237_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [16, 12, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 4 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.6e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[501/561] sub-88025553_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 15, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (8.1e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[502/561] sub-88026949_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (8.6e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[503/561] sub-88026949_ses-2_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 4.7s.
ICA removed components: [0, 3, 5, 6, 8, 10, 11, 14, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

c:\Users\michael\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\decomposition\_fastica.py:127: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(
C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (3.2e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[504/561] sub-88027577_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 8, 9, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (1.9e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[505/561] sub-88027581_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.9e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[506/561] sub-88028661_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (14) and smallest (1e-30) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[507/561] sub-88029733_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 17 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.7e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[508/561] sub-88030505_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.9e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[509/561] sub-88034013_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (2.2e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[510/561] sub-88034057_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 3, 4, 6, 8, 9, 10, 11, 12, 13, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2.7e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[511/561] sub-88035317_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 6, 7, 9, 10, 11, 12, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (1.6e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[512/561] sub-88035949_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 4, 5, 6, 9, 10, 11, 12, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2.9e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[513/561] sub-88036081_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 3, 4, 5, 6, 7, 9, 10, 12, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (8.6e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[514/561] sub-88036081_ses-2_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (3.2e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[515/561] sub-88036265_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 5, 6, 7, 9, 10]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (11) and smallest (5e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 6
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[516/561] sub-88038025_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [1, 5, 7, 8, 9, 11, 12, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 10 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (11) and smallest (1.6e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[517/561] sub-88038473_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 4, 5, 6, 7, 9, 11, 12, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (1e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[518/561] sub-88038609_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (3.1e-34) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[519/561] sub-88038697_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (3.6e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[520/561] sub-88039193_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 6, 7, 9, 10, 12, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (3.5e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[521/561] sub-88039281_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 17 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (4.8e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[522/561] sub-88040901_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 2, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (3e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[523/561] sub-88041305_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 4, 7, 8, 9, 10, 12, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2.2e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[524/561] sub-88041485_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 3, 5, 6, 8, 9, 10, 11, 13, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (7e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[525/561] sub-88041529_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 2, 3, 4, 6, 7, 8, 9, 10, 11, 14, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (9.7e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[526/561] sub-88041849_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 7, 9, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (8.3) and smallest (8.1e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[527/561] sub-88041985_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [1, 2, 9, 10, 11, 12, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 7 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (8.4e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[528/561] sub-88042661_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 4, 5, 6, 10, 11, 12, 14, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 10 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (4e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[529/561] sub-88043017_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (4.4e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[530/561] sub-88044189_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 2, 4, 5, 6, 7, 8, 10, 11, 12]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 10 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (4.7e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[531/561] sub-88044321_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 2, 3, 4, 9, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 8 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (11) and smallest (1.9e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[532/561] sub-88044997_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (7.2e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[533/561] sub-88045173_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 2, 3, 4, 6, 10, 11, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (15) and smallest (3e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[534/561] sub-88046077_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 11, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (2.4e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[535/561] sub-88046393_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (2.5e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 17 ICA components
    Projecting back using 19 PCA components
  → 467 windows

[536/561] sub-88049313_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 2, 3, 8, 9, 10, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (14) and smallest (1.1e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[537/561] sub-88050081_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [3, 4, 5, 8, 9, 10, 11, 13, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (17) and smallest (8.7e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[538/561] sub-88050529_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (16) and smallest (2.1e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[539/561] sub-88050669_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 13 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (6.7e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[540/561] sub-88052241_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 6, 9, 12, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 8 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (6.5e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[541/561] sub-88052421_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (7.5e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[542/561] sub-88053185_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 5, 6, 12, 14, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 7 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (8.5) and smallest (2e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[543/561] sub-88053273_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 7, 9, 10, 13]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 6 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (5.4e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[544/561] sub-88053361_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (16) and smallest (1e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[545/561] sub-88053589_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 14]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (3e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[546/561] sub-88056021_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 2, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (7.5e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[547/561] sub-88057189_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 3, 4, 5, 6, 8, 9, 10, 12, 14, 15]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (5.3e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[548/561] sub-88061417_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [0, 1, 2, 3, 4, 6, 8, 9, 13, 14, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (11) and smallest (1.3e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[549/561] sub-88062861_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (18) and smallest (2.2e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[550/561] sub-88063849_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [1, 2, 5, 7, 8, 9, 10, 11, 12, 15, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (1.2e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[551/561] sub-88064345_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 1, 2, 3, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (5.2e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 466 windows

[552/561] sub-88070417_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.4s.
ICA removed components: [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (4.2e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[553/561] sub-88070825_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 16 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (4.7e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 2
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[554/561] sub-88071361_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [1, 2, 4, 6, 7, 8, 10, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 9 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (14) and smallest (1.4e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[555/561] sub-88071545_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 5, 6, 8, 9, 10, 12, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 11 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (12) and smallest (1.3e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 4
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[556/561] sub-88072845_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 2.4s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 16 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (2.8e-32) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[557/561] sub-88073205_ses-1_restEO  (ADHD-C)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 5, 6, 7, 8, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 12 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (9.5) and smallest (3.1e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[558/561] sub-88074381_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.1s.
ICA removed components: [0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 14 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (13) and smallest (2.3e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[559/561] sub-88075101_ses-1_restEO  (ADHD-H)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [0, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (19) and smallest (2.2e-33) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 1
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[560/561] sub-88075681_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.3s.
ICA removed components: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 15 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (16) and smallest (1.1e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 3
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

[561/561] sub-88076173_ses-1_restEO  (ADHD-I)
Fitting ICA to data using 19 channels (please be patient, this may take a while)
Selecting by number: 18 components
Fitting ICA took 0.2s.
ICA removed components: [4, 5, 8, 13, 14, 15, 16]
Applying ICA to Raw instance
    Transforming to ICA space (18 components)
    Zeroing out 7 ICA components
    Projecting back using 19 PCA components

C:\Users\michael\AppData\Local\Temp\ipykernel_33684\2162253564.py:25: RuntimeWarning: Using n_components=18 (resulting in n_components_=18) may lead to an unstable mixing matrix estimation because the ratio between the largest (7.7) and smallest (1.6e-31) variances is too large (> 1e6); consider setting n_components=0.999999 or an integer <= 5
  ica.fit(raw, picks="eeg", decim=3)

  → 467 windows

==================================================
Total windows written : 163428
Output binary values  : 239,095,164

In [12]:
# Save the output index CSV
output_index_df = pd.DataFrame(output_records)
output_index_df.to_csv(OUTPUT_INDEX, index=False)

print(f"Saved binary → {OUTPUT_BINARY}")
print(f"Saved index  → {OUTPUT_INDEX}")
print(f"\nIndex shape: {output_index_df.shape}")
print(f"\nLabel distribution:")
print(output_index_df['label'].value_counts().to_string())
display(output_index_df.head(10))

Saved binary → D:\DATASETS\cnn-lstm\processed_dataset_binary.bin
Saved index  → D:\DATASETS\cnn-lstm\processed_dataset_index.csv

Index shape: (163428, 14)

Label distribution:
label
ADHD-I     50270
Control    48522
ADHD-H     40810
ADHD-C     23826

,id,label,window,start_idx,length,rows,cols,rel_theta,rel_alpha,rel_fast_alpha,rel_beta,rel_high_beta,tbr,tar
0,v107,Control,0,0,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
1,v107,Control,1,1463,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
2,v107,Control,2,2926,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
3,v107,Control,3,4389,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
4,v107,Control,4,5852,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
5,v107,Control,5,7315,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
6,v107,Control,6,8778,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
7,v107,Control,7,10241,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
8,v107,Control,8,11704,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008
9,v107,Control,9,13167,1463,77,19,0.107009,0.034079,0.021371,0.02265,0.016063,4.724506,3.140008

In [14]:
# Verify: read back the first window from the output binary
verify = np.memmap(OUTPUT_BINARY, dtype='float64', mode='r')
sample = output_index_df.iloc[0]
window_arr = verify[sample['start_idx'] : sample['start_idx'] + sample['length']]\
    .reshape(sample['rows'], sample['cols'])

print(f"Verified window shape: {window_arr.shape}  "
      f"(expected {len(FREQUENCIES)} freqs × {len(ELECTRODE_CHANNELS)} channels)")
print(f"\nFirst 5 freqs × first 5 channels:")
display(pd.DataFrame(
    window_arr[:5, :5],
    index=FREQUENCIES[:5],
    columns=ELECTRODE_CHANNELS[:5],
))

Verified window shape: (77, 19)  (expected 77 freqs × 19 channels)

First 5 freqs × first 5 channels:

             Fp1          Fp2           F3          F4           C3
2.0   267.000197   576.459938  1126.595173  178.910625   134.144174
2.5  1039.491622  1490.554961  1311.906474  554.888633  3200.998414
3.0   510.536204   831.366992  1408.830356   47.281497   584.700500
3.5   748.725232   159.473546  1424.573468  629.678740  1239.338875
4.0    71.641515   637.717579   722.079258  274.251011  1489.789000